import { Inter } from "next/font/google";
import "../globals.css";
import Wrapper from "../_components/layout/Wrapper";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    // const width = useWindowDimensions();
    return (
        <html lang="en">
            <body className={inter.className + "mx-10 md:px-[15px]"}>
                <Wrapper childs={children} />
            </body>
        </html>
    );
}
